travis:
  secure:
    BINSTAR_TOKEN: iTLwZpfylg/D5UByi+FR4SwqbkJPL6r/P5p3mGiSUXfYdO0HHHn5KnOGqe7e+Vd4XBBWlVdN1j6gYgtQdLXySi6mggVgbRm5JGLVxdkp1ZUZPE0pJM4xeb7DHn4yV7gaSci3AFNPT6IAadxu3vBtc8sEQZ+mRCc8CquobrjYbV41o6j5r2bRs1bLaC5EhztJNfaCaW2Th9otMNHeh6Kz64wgu6/mnIesg9DgGwFOtQMUoLc+pzdfZldsTEQxpu9hJ6muhjHLj6dhYPEuPODOK7cd4NYFNqQ4SHhLM5CBW+AjXGJoO5YfWnO6aEVgeoTz1W0cRpXfiS38opiSQqgF7rmp0GfSZJEGaBHkda6aV+iKwtRyfbIP4JIwtJT6Hr/BWxY/LZGMovLYLHx11UQxRAqzIXBznCeWYZX3UMxnoAX+l94ibsK823yyo2Vu98a/b77FKhVrAG4evEVv4pnK3kCKrdLRRb/dPeErD+4duIcHxS0PqCD3bLcfVQe8s7z2dn4NqGz9xJ4SI9C0RQgxzDHaApMkg2uX1aqiYri5XT96WKp1GHP3LWakDLM+ZXnFagQID9XiuxPfjMSBh/7ZfudPfk8LTGknQyJorzr9ISl/PffMC6coOxqvoqpkVo5BTZmL5tZlZ1JnSj4Wl4tmDRLYBTuFm4tfElMnOiXnFtw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
